export const LANGUAGE_TOPICS = {
  Spanish: {
    icon: '🇪🇸',
    color: '#FF6B6B',
    topics: [
      {
        id: 'es-greetings',
        name: 'Greetings & Introductions',
        concept: 'Vocabulary',
        description: 'Learn how to greet people and introduce yourself in Spanish',
        example: '¡Hola! Me llamo Juan. ¿Cómo estás?',
        level: 'Beginner',
      },
      {
        id: 'es-numbers',
        name: 'Numbers & Counting',
        concept: 'Vocabulary',
        description: 'Master numbers from 1 to 100 and basic counting',
        example: 'Uno, dos, tres, cuatro, cinco...',
        level: 'Beginner',
      },
      {
        id: 'es-food',
        name: 'Food & Restaurants',
        concept: 'Vocabulary',
        description: 'Order food and talk about meals in Spanish',
        example: 'Quisiera una paella, por favor.',
        level: 'Beginner',
      },
      {
        id: 'es-travel',
        name: 'Travel & Directions',
        concept: 'Conversation',
        description: 'Navigate cities and ask for directions',
        example: '¿Dónde está la estación de tren?',
        level: 'Intermediate',
      },
      {
        id: 'es-past-tense',
        name: 'Past Tense',
        concept: 'Grammar',
        description: 'Talk about past events using preterite and imperfect',
        example: 'Ayer fui al mercado y compré frutas.',
        level: 'Intermediate',
      },
    ],
  },
  French: {
    icon: '🇫🇷',
    color: '#4ECDC4',
    topics: [
      {
        id: 'fr-greetings',
        name: 'Greetings & Politeness',
        concept: 'Vocabulary',
        description: 'Learn essential French greetings and polite expressions',
        example: 'Bonjour! Comment allez-vous?',
        level: 'Beginner',
      },
      {
        id: 'fr-numbers',
        name: 'Numbers & Time',
        concept: 'Vocabulary',
        description: 'Count in French and tell time',
        example: 'Il est trois heures et demie.',
        level: 'Beginner',
      },
      {
        id: 'fr-food',
        name: 'Café & Cuisine',
        concept: 'Vocabulary',
        description: 'Order at a café and discuss French cuisine',
        example: 'Je voudrais un café au lait, s\'il vous plaît.',
        level: 'Beginner',
      },
      {
        id: 'fr-travel',
        name: 'Travel & Transportation',
        concept: 'Conversation',
        description: 'Navigate French cities and use public transport',
        example: 'Où est la gare? Je voudrais un billet pour Paris.',
        level: 'Intermediate',
      },
      {
        id: 'fr-subjunctive',
        name: 'Subjunctive Mood',
        concept: 'Grammar',
        description: 'Express wishes, emotions, and uncertainty',
        example: 'Je veux que tu sois heureux.',
        level: 'Advanced',
      },
    ],
  },
  Japanese: {
    icon: '🇯🇵',
    color: '#FF9F43',
    topics: [
      {
        id: 'ja-greetings',
        name: 'Greetings & Introductions',
        concept: 'Vocabulary',
        description: 'Learn basic Japanese greetings and self-introduction',
        example: 'こんにちは！私はジョンです。よろしくお願いします。',
        level: 'Beginner',
      },
      {
        id: 'ja-numbers',
        name: 'Numbers & Counting',
        concept: 'Vocabulary',
        description: 'Master Japanese numbers and counters',
        example: 'いち、に、さん、し、ご...',
        level: 'Beginner',
      },
      {
        id: 'ja-food',
        name: 'Food & Dining',
        concept: 'Vocabulary',
        description: 'Order food and discuss Japanese cuisine',
        example: 'ラーメンを一つお願いします。',
        level: 'Beginner',
      },
      {
        id: 'ja-travel',
        name: 'Travel & Directions',
        concept: 'Conversation',
        description: 'Navigate Japan and ask for directions',
        example: '駅はどこですか？',
        level: 'Intermediate',
      },
      {
        id: 'ja-particles',
        name: 'Particles (は, が, を)',
        concept: 'Grammar',
        description: 'Master the essential Japanese particles',
        example: '私は寿司を食べます。',
        level: 'Intermediate',
      },
    ],
  },
  Korean: {
    icon: '🇰🇷',
    color: '#A855F7',
    topics: [
      {
        id: 'ko-greetings',
        name: 'Greetings & Introductions',
        concept: 'Vocabulary',
        description: 'Learn Korean greetings and introduce yourself',
        example: '안녕하세요! 저는 존입니다.',
        level: 'Beginner',
      },
      {
        id: 'ko-numbers',
        name: 'Numbers & Counting',
        concept: 'Vocabulary',
        description: 'Master Korean native and Sino-Korean numbers',
        example: '하나, 둘, 셋, 넷, 다섯...',
        level: 'Beginner',
      },
      {
        id: 'ko-food',
        name: 'Food & Dining',
        concept: 'Vocabulary',
        description: 'Order food and discuss Korean cuisine',
        example: '김치찌개 하나 주세요.',
        level: 'Beginner',
      },
      {
        id: 'ko-travel',
        name: 'Travel & Directions',
        concept: 'Conversation',
        description: 'Navigate Korea and ask for directions',
        example: '지하철역이 어디에 있어요?',
        level: 'Intermediate',
      },
      {
        id: 'ko-honorifics',
        name: 'Honorifics & Politeness',
        concept: 'Grammar',
        description: 'Learn formal and informal speech levels',
        example: '감사합니다 vs 고마워',
        level: 'Intermediate',
      },
    ],
  },
  German: {
    icon: '🇩🇪',
    color: '#FFD93D',
    topics: [
      {
        id: 'de-greetings',
        name: 'Greetings & Introductions',
        concept: 'Vocabulary',
        description: 'Learn German greetings and introduce yourself',
        example: 'Hallo! Ich heiße Hans. Wie geht es dir?',
        level: 'Beginner',
      },
      {
        id: 'de-numbers',
        name: 'Numbers & Counting',
        concept: 'Vocabulary',
        description: 'Count in German and use numbers in daily life',
        example: 'eins, zwei, drei, vier, fünf...',
        level: 'Beginner',
      },
      {
        id: 'de-food',
        name: 'Food & Restaurants',
        concept: 'Vocabulary',
        description: 'Order food and discuss German cuisine',
        example: 'Ich möchte eine Bratwurst, bitte.',
        level: 'Beginner',
      },
      {
        id: 'de-travel',
        name: 'Travel & Transportation',
        concept: 'Conversation',
        description: 'Navigate German cities and use public transport',
        example: 'Wo ist der Bahnhof?',
        level: 'Intermediate',
      },
      {
        id: 'de-cases',
        name: 'Nominative, Accusative, Dative',
        concept: 'Grammar',
        description: 'Master German noun cases',
        example: 'Der Mann gibt dem Kind den Ball.',
        level: 'Intermediate',
      },
    ],
  },
  Italian: {
    icon: '🇮🇹',
    color: '#00D4FF',
    topics: [
      {
        id: 'it-greetings',
        name: 'Greetings & Introductions',
        concept: 'Vocabulary',
        description: 'Learn Italian greetings and introduce yourself',
        example: 'Ciao! Mi chiamo Marco. Come stai?',
        level: 'Beginner',
      },
      {
        id: 'it-numbers',
        name: 'Numbers & Counting',
        concept: 'Vocabulary',
        description: 'Count in Italian and use numbers daily',
        example: 'uno, due, tre, quattro, cinque...',
        level: 'Beginner',
      },
      {
        id: 'it-food',
        name: 'Food & Dining',
        concept: 'Vocabulary',
        description: 'Order food and discuss Italian cuisine',
        example: 'Vorrei una pizza margherita, per favore.',
        level: 'Beginner',
      },
      {
        id: 'it-travel',
        name: 'Travel & Directions',
        concept: 'Conversation',
        description: 'Navigate Italy and ask for directions',
        example: 'Dov\'è la stazione?',
        level: 'Intermediate',
      },
      {
        id: 'it-verbs',
        name: 'Verb Conjugation',
        concept: 'Grammar',
        description: 'Master Italian verb conjugations',
        example: 'Io parlo, tu parli, lui parla...',
        level: 'Intermediate',
      },
    ],
  },
  Chinese: {
    icon: '🇨🇳',
    color: '#FF4757',
    topics: [
      {
        id: 'zh-greetings',
        name: 'Greetings & Introductions',
        concept: 'Vocabulary',
        description: 'Learn Chinese greetings and introduce yourself',
        example: '你好！我叫约翰。',
        level: 'Beginner',
      },
      {
        id: 'zh-numbers',
        name: 'Numbers & Counting',
        concept: 'Vocabulary',
        description: 'Master Chinese numbers and counting',
        example: '一二三四五...',
        level: 'Beginner',
      },
      {
        id: 'zh-food',
        name: 'Food & Dining',
        concept: 'Vocabulary',
        description: 'Order food and discuss Chinese cuisine',
        example: '我要一碗牛肉面。',
        level: 'Beginner',
      },
      {
        id: 'zh-travel',
        name: 'Travel & Directions',
        concept: 'Conversation',
        description: 'Navigate China and ask for directions',
        example: '地铁站在哪里？',
        level: 'Intermediate',
      },
      {
        id: 'zh-tones',
        name: 'Tones & Pronunciation',
        concept: 'Grammar',
        description: 'Master the four Mandarin tones',
        example: 'mā, má, mǎ, mà',
        level: 'Beginner',
      },
    ],
  },
  English: {
    icon: '🇬🇧',
    color: '#53C691',
    topics: [
      {
        id: 'en-greetings',
        name: 'Greetings & Introductions',
        concept: 'Vocabulary',
        description: 'Learn English greetings and introduce yourself',
        example: 'Hello! My name is John. Nice to meet you!',
        level: 'Beginner',
      },
      {
        id: 'en-numbers',
        name: 'Numbers & Counting',
        concept: 'Vocabulary',
        description: 'Master English numbers and counting',
        example: 'one, two, three, four, five...',
        level: 'Beginner',
      },
      {
        id: 'en-food',
        name: 'Food & Restaurants',
        concept: 'Vocabulary',
        description: 'Order food and discuss English cuisine',
        example: 'I would like a cup of tea, please.',
        level: 'Beginner',
      },
      {
        id: 'en-travel',
        name: 'Travel & Directions',
        concept: 'Conversation',
        description: 'Navigate English-speaking countries',
        example: 'Excuse me, where is the train station?',
        level: 'Intermediate',
      },
      {
        id: 'en-tenses',
        name: 'Verb Tenses',
        concept: 'Grammar',
        description: 'Master English verb tenses',
        example: 'I walk, I walked, I will walk, I am walking...',
        level: 'Intermediate',
      },
    ],
  },
  Portuguese: {
    icon: '🇧🇷',
    color: '#B8FF3C',
    topics: [
      {
        id: 'pt-greetings',
        name: 'Greetings & Introductions',
        concept: 'Vocabulary',
        description: 'Learn Portuguese greetings and introduce yourself',
        example: 'Olá! Meu nome é João. Como vai?',
        level: 'Beginner',
      },
      {
        id: 'pt-numbers',
        name: 'Numbers & Counting',
        concept: 'Vocabulary',
        description: 'Count in Portuguese and use numbers daily',
        example: 'um, dois, três, quatro, cinco...',
        level: 'Beginner',
      },
      {
        id: 'pt-food',
        name: 'Food & Dining',
        concept: 'Vocabulary',
        description: 'Order food and discuss Brazilian cuisine',
        example: 'Eu gostaria de uma feijoada, por favor.',
        level: 'Beginner',
      },
      {
        id: 'pt-travel',
        name: 'Travel & Directions',
        concept: 'Conversation',
        description: 'Navigate Brazil and ask for directions',
        example: 'Onde fica a praia?',
        level: 'Intermediate',
      },
      {
        id: 'pt-verbs',
        name: 'Verb Conjugation',
        concept: 'Grammar',
        description: 'Master Portuguese verb conjugations',
        example: 'Eu falo, tu falas, ele fala...',
        level: 'Intermediate',
      },
    ],
  },
};